/**
 * 规则标记相关类型定义
 * 用于单文件适配器的部分更新支持
 */

/**
 * 单条规则区块
 */
export interface RuleBlock {
  /** 规则源 ID */
  sourceId: string;
  /** 规则 ID */
  ruleId: string;
  /** 规则优先级 */
  priority?: string;
  /** 区块开始行号（0-based） */
  startLine: number;
  /** 区块结束行号（0-based） */
  endLine: number;
  /** 区块原始内容（包含标记） */
  rawContent: string;
  /** 规则内容（不含标记） */
  content: string;
}

/**
 * 规则源区块（包含多条规则）
 */
export interface SourceBlock {
  /** 规则源 ID */
  sourceId: string;
  /** 区块内规则数量 */
  count: number;
  /** 区块开始行号（0-based） */
  startLine: number;
  /** 区块结束行号（0-based） */
  endLine: number;
  /** 包含的规则区块 */
  rules: RuleBlock[];
  /** 区块原始内容（包含标记） */
  rawContent: string;
}

/**
 * 用户自定义内容区块
 */
export interface UserContentBlock {
  /** 区块开始行号（0-based） */
  startLine: number;
  /** 区块结束行号（0-based） */
  endLine: number;
  /** 区块原始内容（包含标记） */
  rawContent: string;
  /** 内容（不含标记） */
  content: string;
}

/**
 * 文件解析结果
 */
export interface ParsedMarkedFile {
  /** 文件头部内容（第一个 SOURCE 区块之前的内容） */
  header: string;
  /** 规则源区块列表 */
  sourceBlocks: SourceBlock[];
  /** 用户自定义内容区块（可选） */
  userContent: UserContentBlock | null;
  /** 是否包含有效标记（用于判断是否支持部分更新） */
  hasValidMarkers: boolean;
}

/**
 * 标记常量
 */
export const MARKER = {
  /** 规则源区块开始标记 */
  BEGIN_SOURCE: '<!-- BEGIN_SOURCE',
  /** 规则源区块结束标记 */
  END_SOURCE: '<!-- END_SOURCE',
  /** 单条规则开始标记 */
  BEGIN_RULE: '<!-- BEGIN_RULE',
  /** 单条规则结束标记 */
  END_RULE: '<!-- END_RULE -->',
  /** 用户内容开始标记 */
  BEGIN_USER_CONTENT: '<!-- BEGIN_USER_CONTENT -->',
  /** 用户内容结束标记 */
  END_USER_CONTENT: '<!-- END_USER_CONTENT -->',
  /** 生成器签名 */
  GENERATOR_SIGNATURE: '<!-- Generated by Turbo AI Rules',
} as const;

/**
 * 部分更新选项
 */
export interface PartialUpdateOptions {
  /** 目标规则源 ID 列表（只更新这些源） */
  targetSourceIds: string[];
  /** 是否保留用户内容 */
  preserveUserContent?: boolean;
  /** 是否保留未指定的源 */
  preserveOtherSources?: boolean;
}

/**
 * 生成标记内容的选项
 */
export interface MarkerGeneratorOptions {
  /** 是否生成规则源区块标记 */
  includeSourceMarkers?: boolean;
  /** 是否生成单条规则标记 */
  includeRuleMarkers?: boolean;
  /** 是否包含优先级信息 */
  includePriority?: boolean;
  /** 顶层块标记（包裹所有自动生成的内容） */
  blockMarkers?: {
    begin: string;
    end: string;
  };
  /** 用户规则源包裹标记（可选，用于 sourceId='user-rules'） */
  userRulesMarkers?: {
    begin: string;
    end: string;
  };
}
