/**
 * GitHub Copilot 适配器
 * 生成 .github/copilot-instructions.md 文件
 */

import type { ParsedRule } from '../types/rules';
import { Logger } from '../utils/logger';
import type { GeneratedConfig } from './AIToolAdapter';
import { BaseAdapter } from './AIToolAdapter';

/**
 * GitHub Copilot 适配器
 *
 * GitHub Copilot 使用 .github/copilot-instructions.md 文件
 * 支持更结构化的 Markdown 格式，可以包含代码示例
 */
export class CopilotAdapter extends BaseAdapter {
  readonly name = 'GitHub Copilot';
  readonly enabled: boolean;

  constructor(enabled: boolean = true) {
    super();
    this.enabled = enabled;
  }

  /**
   * 生成 .github/copilot-instructions.md 文件内容
   */
  async generate(rules: ParsedRule[]): Promise<GeneratedConfig> {
    Logger.info('Generating GitHub Copilot configuration', { ruleCount: rules.length });

    if (rules.length === 0) {
      Logger.warn('No rules to generate for GitHub Copilot');
      return {
        filePath: this.getFilePath(),
        content: this.generateEmptyConfig(),
        generatedAt: new Date(),
        ruleCount: 0,
      };
    }

    // 按优先级排序
    const sortedRules = this.sortByPriority(rules);

    // 生成内容
    let content = '';

    // 添加文件头部（Copilot 使用不同的标题）
    content += this.generateMetadata(rules.length);
    content += '# GitHub Copilot Instructions\n\n';
    content += '> This file provides coding guidelines and rules for GitHub Copilot.\n';
    content += '> Generated by Turbo AI Rules extension.\n\n';

    // 添加目录（Table of Contents）以便快速导航
    content += this.generateTableOfContents(sortedRules);

    // 添加规则
    content += this.formatRulesForCopilot(sortedRules);

    Logger.info('GitHub Copilot configuration generated', {
      ruleCount: rules.length,
      contentLength: content.length,
    });

    return {
      filePath: this.getFilePath(),
      content,
      generatedAt: new Date(),
      ruleCount: rules.length,
    };
  }

  /**
   * 格式化规则为 Copilot 格式
   */
  private formatRulesForCopilot(rules: ParsedRule[]): string {
    return rules
      .map((rule) => {
        // 直接使用规则的原始内容，不添加额外的标题
        // rawContent 已经包含了完整的 frontmatter 和内容
        const content = (rule.rawContent || rule.content)?.trim() || '';
        return content;
      })
      .join('\n\n---\n\n');
  }

  /**
   * 生成空配置
   */
  private generateEmptyConfig(): string {
    return (
      this.generateMetadata(0) +
      '# GitHub Copilot Instructions\n\n' +
      '> No rules configured yet.\n'
    );
  }

  /**
   * 验证配置文件
   */
  validate(content: string): boolean {
    if (!super.validate(content)) {
      return false;
    }

    // 检查是否包含标题
    return content.includes('# ') || content.includes('## ');
  }

  /**
   * 获取文件路径
   */
  getFilePath(): string {
    return '.github/copilot-instructions.md';
  }
}
