/**
 * GitHub Copilot 适配器
 * 生成 .github/copilot-instructions.md 文件
 * 支持规则源标记，实现部分更新
 */

import type { ParsedRule } from '../types/rules';
import { Logger } from '../utils/logger';
import { generateMarkedFileContent, groupRulesBySource } from '../utils/ruleMarkerGenerator';
import type { GeneratedConfig } from './AIToolAdapter';
import { BaseAdapter } from './AIToolAdapter';

/**
 * GitHub Copilot 适配器
 *
 * GitHub Copilot 使用 .github/copilot-instructions.md 文件
 * 支持更结构化的 Markdown 格式，可以包含代码示例
 * 支持规则源标记，实现部分更新
 */
export class CopilotAdapter extends BaseAdapter {
  readonly name = 'GitHub Copilot';
  readonly enabled: boolean;

  constructor(enabled: boolean = true) {
    super();
    this.enabled = enabled;
  }

  /**
   * 生成 .github/copilot-instructions.md 文件内容
   * 使用规则源标记格式，支持部分更新
   */
  async generate(rules: ParsedRule[], _allRules?: ParsedRule[]): Promise<GeneratedConfig> {
    Logger.info('Generating GitHub Copilot configuration', { ruleCount: rules.length });

    // 加载用户规则
    const userRules = await this.loadUserRules();
    if (userRules.length > 0) {
      Logger.info('Loaded user rules for Copilot', { userRuleCount: userRules.length });
    }

    // 合并远程规则和用户规则
    const allRules = this.mergeWithUserRules(rules, userRules);
    const totalCount = allRules.length;

    if (totalCount === 0) {
      Logger.warn('No rules to generate for GitHub Copilot');
      return {
        filePath: this.getFilePath(),
        content: this.generateEmptyConfig(),
        generatedAt: new Date(),
        ruleCount: 0,
      };
    }

    // 排序已在 mergeWithUserRules 中完成
    const sortedRules = allRules;

    // 生成头部内容（不含元数据，元数据由 generateMarkedFileContent 生成）
    const headerContent = this.generateCopilotHeader(sortedRules);

    // 使用带标记的格式生成内容
    const content = generateMarkedFileContent(sortedRules, headerContent);

    Logger.info('GitHub Copilot configuration generated with markers', {
      remoteRuleCount: rules.length,
      userRuleCount: userRules.length,
      totalRuleCount: totalCount,
      sourceCount: groupRulesBySource(sortedRules).size,
      contentLength: content.length,
    });

    return {
      filePath: this.getFilePath(),
      content,
      generatedAt: new Date(),
      ruleCount: totalCount,
    };
  }

  /**
   * 生成 Copilot 特有的头部内容
   */
  private generateCopilotHeader(rules: ParsedRule[]): string {
    let header = '# GitHub Copilot Instructions\n\n';
    header += '> This file provides coding guidelines and rules for GitHub Copilot.\n';
    header += '> Generated by Turbo AI Rules extension.\n\n';

    // 添加目录
    header += this.generateTableOfContents(rules);

    return header;
  }

  /**
   * 生成空配置
   */
  private generateEmptyConfig(): string {
    return (
      this.generateMetadata(0) +
      '# GitHub Copilot Instructions\n\n' +
      '> No rules configured yet.\n'
    );
  }

  /**
   * 验证配置文件
   */
  validate(content: string): boolean {
    if (!super.validate(content)) {
      return false;
    }

    // 检查是否包含标题
    return content.includes('# ') || content.includes('## ');
  }

  /**
   * 获取文件路径
   */
  getFilePath(): string {
    return '.github/copilot-instructions.md';
  }
}
