/**
 * userRulesProtection 工具函数单元测试
 */

import { describe, expect, it } from 'vitest';

import {
  BLOCK_MARKERS,
  detectConflicts,
  extractPrefix,
  extractUserContent,
  filterAutoGeneratedFiles,
  isAutoGeneratedFile,
  isUserDefinedFile,
  mergeContent,
  PREFIX_RANGES,
  suggestAlternativeFilename,
  UserRulesProtectionConfig,
} from '@/utils/userRulesProtection';

describe('userRulesProtection 单元测试', () => {
  const enabledConfig: UserRulesProtectionConfig = {
    enabled: true,
  };

  const disabledConfig: UserRulesProtectionConfig = {
    enabled: false,
  };

  const customRangeConfig: UserRulesProtectionConfig = {
    enabled: true,
    userPrefixRange: {
      min: 900,
      max: 950,
    },
  };

  describe('extractPrefix', () => {
    it('应该提取数字前缀', () => {
      expect(extractPrefix('001-overview.md')).toBe(1);
      expect(extractPrefix('050-typescript.mdc')).toBe(50);
      expect(extractPrefix('500-advanced.md')).toBe(500);
      expect(extractPrefix('85000-user-rules.md')).toBe(85000);
      expect(extractPrefix('99999-custom.md')).toBe(99999);
    });

    it('应该处理没有前缀的文件名', () => {
      expect(extractPrefix('readme.md')).toBeNull();
      expect(extractPrefix('my-rules.mdc')).toBeNull();
      expect(extractPrefix('no-prefix.md')).toBeNull();
    });

    it('应该处理边界情况', () => {
      expect(extractPrefix('0-zero.md')).toBe(0);
      expect(extractPrefix('1-one.md')).toBe(1);
      expect(extractPrefix('9999-large.md')).toBe(9999);
    });

    it('应该忽略中间的数字', () => {
      expect(extractPrefix('abc-123-def.md')).toBeNull();
      expect(extractPrefix('no-001-middle.md')).toBeNull();
    });
  });

  describe('isUserDefinedFile', () => {
    it('应该识别用户定义范围的文件(80000-99999)', () => {
      expect(isUserDefinedFile('80000-user-start.md', enabledConfig)).toBe(true);
      expect(isUserDefinedFile('85000-my-rules.md', enabledConfig)).toBe(true);
      expect(isUserDefinedFile('99999-user-end.md', enabledConfig)).toBe(true);
    });

    it('应该拒绝自动生成范围的文件(0-79999)', () => {
      expect(isUserDefinedFile('00000-auto-start.md', enabledConfig)).toBe(false);
      expect(isUserDefinedFile('50000-mid.md', enabledConfig)).toBe(false);
      expect(isUserDefinedFile('79999-auto-end.md', enabledConfig)).toBe(false);
    });

    it('应该保守地将无前缀文件视为用户文件', () => {
      expect(isUserDefinedFile('readme.md', enabledConfig)).toBe(true);
      expect(isUserDefinedFile('my-custom-rules.md', enabledConfig)).toBe(true);
    });

    it('应该在禁用保护时返回 false', () => {
      expect(isUserDefinedFile('85000-user-rules.md', disabledConfig)).toBe(false);
      expect(isUserDefinedFile('readme.md', disabledConfig)).toBe(false);
    });

    it('应该支持自定义范围', () => {
      expect(isUserDefinedFile('900-in-range.md', customRangeConfig)).toBe(true);
      expect(isUserDefinedFile('950-in-range.md', customRangeConfig)).toBe(true);
      expect(isUserDefinedFile('85000-out-range.md', customRangeConfig)).toBe(false);
      expect(isUserDefinedFile('960-out-range.md', customRangeConfig)).toBe(false);
    });
  });

  describe('isAutoGeneratedFile', () => {
    it('应该识别自动生成范围的文件', () => {
      expect(isAutoGeneratedFile('000-start.md', enabledConfig)).toBe(true);
      expect(isAutoGeneratedFile('500-middle.md', enabledConfig)).toBe(true);
      expect(isAutoGeneratedFile('79999-end.md', enabledConfig)).toBe(true);
    });

    it('应该拒绝用户定义范围的文件', () => {
      expect(isAutoGeneratedFile('80000-user.md', enabledConfig)).toBe(false);
      expect(isAutoGeneratedFile('99999-user.md', enabledConfig)).toBe(false);
    });

    it('应该保守地将无前缀文件视为用户文件', () => {
      expect(isAutoGeneratedFile('readme.md', enabledConfig)).toBe(false);
    });

    it('应该在禁用保护时返回 true', () => {
      expect(isAutoGeneratedFile('85000-user.md', disabledConfig)).toBe(true);
      expect(isAutoGeneratedFile('readme.md', disabledConfig)).toBe(true);
    });
  });

  describe('filterAutoGeneratedFiles', () => {
    it('应该过滤出自动生成的文件', () => {
      const files = [
        '/path/001-auto.md',
        '/path/500-auto.md',
        '/path/85000-user.md',
        '/path/99999-user.md',
        '/path/readme.md',
      ];

      const result = filterAutoGeneratedFiles(files, enabledConfig);

      expect(result).toHaveLength(2);
      expect(result).toContain('/path/001-auto.md');
      expect(result).toContain('/path/500-auto.md');
    });

    it('应该在禁用保护时返回所有文件', () => {
      const files = ['/path/00001-auto.md', '/path/85000-user.md', '/path/readme.md'];

      const result = filterAutoGeneratedFiles(files, disabledConfig);

      expect(result).toHaveLength(3);
    });

    it('应该处理空数组', () => {
      const result = filterAutoGeneratedFiles([], enabledConfig);
      expect(result).toHaveLength(0);
    });
  });

  describe('extractUserContent', () => {
    it('应该提取用户内容(在块外的内容)', () => {
      const content = [
        'User header content',
        '',
        '<!-- TURBO-AI-RULES:BEGIN -->',
        'Auto-generated rules',
        '<!-- TURBO-AI-RULES:END -->',
        '',
        'User footer content',
      ].join('\n');

      const { autoContent, userContent } = extractUserContent(content, enabledConfig);

      expect(autoContent).toContain('Auto-generated rules');
      expect(userContent).toContain('User header content');
      expect(userContent).toContain('User footer content');
      expect(userContent).not.toContain('TURBO-AI-RULES');
    });

    it('应该处理多个自动生成块', () => {
      const content = [
        'User content 1',
        '<!-- TURBO-AI-RULES:BEGIN -->',
        'Auto block 1',
        '<!-- TURBO-AI-RULES:END -->',
        'User content 2',
        '<!-- TURBO-AI-RULES:BEGIN -->',
        'Auto block 2',
        '<!-- TURBO-AI-RULES:END -->',
        'User content 3',
      ].join('\n');

      const { autoContent, userContent } = extractUserContent(content, enabledConfig);

      expect(autoContent).toContain('Auto block 1');
      expect(autoContent).toContain('Auto block 2');
      expect(userContent).toContain('User content 1');
      expect(userContent).toContain('User content 2');
      expect(userContent).toContain('User content 3');
    });

    it('应该处理没有自动生成块的内容', () => {
      const content = 'Only user content here';

      const { autoContent, userContent } = extractUserContent(content, enabledConfig);

      expect(autoContent).toBe('');
      expect(userContent).toBe('Only user content here');
    });

    it('应该支持自定义块标记', () => {
      const customConfig: UserRulesProtectionConfig = {
        enabled: true,
        blockMarkers: {
          begin: '<!-- AUTO:START -->',
          end: '<!-- AUTO:END -->',
        },
      };

      const content = [
        'User content',
        '<!-- AUTO:START -->',
        'Auto content',
        '<!-- AUTO:END -->',
      ].join('\n');

      const { autoContent, userContent } = extractUserContent(content, customConfig);

      expect(autoContent).toContain('Auto content');
      expect(userContent).toBe('User content');
    });
  });

  describe('mergeContent', () => {
    it('应该合并自动和用户内容', () => {
      const autoContent = 'Auto-generated rules';
      const userContent = 'My custom rules';

      const merged = mergeContent(autoContent, userContent, enabledConfig);

      expect(merged).toContain(BLOCK_MARKERS.begin);
      expect(merged).toContain(BLOCK_MARKERS.end);
      expect(merged).toContain('Auto-generated rules');
      expect(merged).toContain('My custom rules');
      expect(merged).toContain('WARNING'); // 警告信息
    });

    it('应该在没有用户内容时只返回包裹的自动内容', () => {
      const autoContent = 'Auto-generated rules';
      const userContent = '';

      const merged = mergeContent(autoContent, userContent, enabledConfig);

      expect(merged).toContain(BLOCK_MARKERS.begin);
      expect(merged).toContain(BLOCK_MARKERS.end);
      expect(merged).toContain('Auto-generated rules');
      expect(merged).not.toContain('Your Custom Rules'); // 不应该有模板
    });

    it('应该包含时间戳和警告信息', () => {
      const merged = mergeContent('auto', 'user', enabledConfig);

      expect(merged).toMatch(/Generated by Turbo AI Rules at \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
      expect(merged).toContain('WARNING: Auto-generated content');
      expect(merged).toContain('警告：自动生成内容');
    });

    it('应该支持自定义块标记', () => {
      const customConfig: UserRulesProtectionConfig = {
        enabled: true,
        blockMarkers: {
          begin: '<!-- CUSTOM:START -->',
          end: '<!-- CUSTOM:END -->',
        },
      };

      const merged = mergeContent('auto', 'user', customConfig);

      expect(merged).toContain('<!-- CUSTOM:START -->');
      expect(merged).toContain('<!-- CUSTOM:END -->');
    });
  });

  describe('detectConflicts', () => {
    it('应该检测用户范围的文件冲突', () => {
      const existingFiles = ['/path/85000-user.md', '/path/90000-custom.md'];
      const newFiles = ['/path/85000-user.md', '/path/00001-auto.md'];

      const conflicts = detectConflicts(existingFiles, newFiles, enabledConfig);

      expect(conflicts).toHaveLength(1);
      expect(conflicts).toContain('85000-user.md');
    });

    it('应该忽略自动生成范围的冲突', () => {
      const existingFiles = ['/path/001-auto.md', '/path/500-auto.md'];
      const newFiles = ['/path/001-auto.md', '/path/500-auto.md'];

      const conflicts = detectConflicts(existingFiles, newFiles, enabledConfig);

      expect(conflicts).toHaveLength(0);
    });

    it('应该在禁用保护时返回空数组', () => {
      const existingFiles = ['/path/85000-user.md'];
      const newFiles = ['/path/85000-user.md'];

      const conflicts = detectConflicts(existingFiles, newFiles, disabledConfig);

      expect(conflicts).toHaveLength(0);
    });

    it('应该处理空文件列表', () => {
      const conflicts = detectConflicts([], [], enabledConfig);
      expect(conflicts).toHaveLength(0);
    });
  });

  describe('suggestAlternativeFilename', () => {
    it('应该建议自动范围内的文件名', () => {
      const result = suggestAlternativeFilename('85000-rules.md', []);

      const prefix = extractPrefix(result);
      expect(prefix).not.toBeNull();
      expect(prefix!).toBeLessThanOrEqual(PREFIX_RANGES.AUTO_MAX);
      expect(result).toContain('rules.md');
    });

    it('应该避免已存在的前缀', () => {
      const existingFiles = [
        '/path/79999-exist.md',
        '/path/79998-exist.md',
        '/path/79997-exist.md',
      ];

      const result = suggestAlternativeFilename('85000-new.md', existingFiles);

      const prefix = extractPrefix(result);
      expect(prefix).toBe(79996); // 第一个未被占用的
      expect(result).toContain('new.md');
    });

    it('应该保持非用户范围的文件名不变', () => {
      const result = suggestAlternativeFilename('500-auto.md', []);
      expect(result).toBe('500-auto.md');
    });

    it('应该保持无前缀的文件名不变', () => {
      const result = suggestAlternativeFilename('readme.md', []);
      expect(result).toBe('readme.md');
    });

    it('应该正确格式化三位数前缀', () => {
      const result = suggestAlternativeFilename('850-test.md', []);
      const match = result.match(/^(\d{3})-/);

      expect(match).not.toBeNull();
      expect(match![1].length).toBe(3); // 三位数
    });
  });

  describe('常量验证', () => {
    it('应该有正确的默认块标记', () => {
      expect(BLOCK_MARKERS.begin).toBe('<!-- TURBO-AI-RULES:BEGIN -->');
      expect(BLOCK_MARKERS.end).toBe('<!-- TURBO-AI-RULES:END -->');
    });

    it('应该有正确的前缀范围', () => {
      expect(PREFIX_RANGES.AUTO_MIN).toBe(0);
      expect(PREFIX_RANGES.AUTO_MAX).toBe(79999);
      expect(PREFIX_RANGES.USER_MIN).toBe(80000);
      expect(PREFIX_RANGES.USER_MAX).toBe(99999);
    });
  });

  describe('集成场景', () => {
    it('应该支持完整的文件保护流程', () => {
      // 1. 检测文件是否为用户文件
      const filename = '85000-my-rules.md';
      expect(isUserDefinedFile(filename, enabledConfig)).toBe(true);

      // 2. 过滤时排除用户文件
      const files = ['/path/00001-auto.md', `/path/${filename}`];
      const filtered = filterAutoGeneratedFiles(files, enabledConfig);
      expect(filtered).not.toContain(`/path/${filename}`);

      // 3. 建议替代文件名
      const alternative = suggestAlternativeFilename(filename, []);
      expect(isAutoGeneratedFile(alternative, enabledConfig)).toBe(true);
    });

    it('应该支持完整的内容保护流程', () => {
      // 1. 从现有文件提取用户内容
      const existingContent = [
        '<!-- TURBO-AI-RULES:BEGIN -->',
        'Old auto content',
        '<!-- TURBO-AI-RULES:END -->',
        'My custom rules',
      ].join('\n');

      const { userContent } = extractUserContent(existingContent, enabledConfig);
      expect(userContent).toContain('My custom rules');

      // 2. 合并新的自动内容和用户内容
      const merged = mergeContent('New auto content', userContent, enabledConfig);
      expect(merged).toContain('New auto content');
      expect(merged).toContain('My custom rules');
      expect(merged).not.toContain('Old auto content');
    });
  });
});
